version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dentalflow-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: dentalflow
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: dentalflow-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: dentalflow-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      PORT: 5000
      CLIENT_URL: http://localhost:3000
      MONGODB_URI: mongodb://mongodb:27017/dentalflow
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: prod_access_secret_key_32_characters_minimum_len!
      JWT_REFRESH_SECRET: prod_refresh_secret_key_32_characters_minimum_len!
      JWT_ACCESS_EXPIRATION: 15m
      JWT_REFRESH_EXPIRATION_DAYS: 7
    depends_on:
      - mongodb
      - redis

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: dentalflow-web
    restart: unless-stopped
    ports:
      - '3000:80'
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:5000/api/v1
    depends_on:
      - api

volumes:
  mongodb_data:
  redis_data:
